name: chat-app

services:
  backend:
    build: .
    container_name: chat-app
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./app:/srv/project/app
      - ./scripts:/srv/project/scripts
      - ./alembic.ini:/srv/project/alembic.ini
      - ./migrations:/srv/project/migrations
      - ./tests:/srv/project/tests
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
