"""Initial migration

Revision ID: 2b43646a8f92
Revises: 
Create Date: 2025-05-19 22:40:45.389527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b43646a8f92'
down_revision = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False, comment='Уникальный идентификатор чата'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название чата'),
    sa.Column('is_group', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг группового чата (True - группа, False - личный)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания чата'),
    sa.PrimaryKeyConstraint('id'),
    comment='Чаты пользователей'
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False, comment='Уникальный идентификатор пользователя'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Username пользователя'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email пользователя'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Хэшированный пароль'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата регистрации'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.PrimaryKeyConstraint('id'),
    comment='Пользователи системы'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False, comment='Уникальный идентификатор группы'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='ID связанного чата'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название группы'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='ID создателя группы'),
    sa.Column('members', sa.JSON(), nullable=False, comment='Список ID участников группы'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания группы'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id'),
    comment='Групповые чаты'
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False, comment='Уникальный идентификатор сообщения'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='ID чата'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='ID отправителя'),
    sa.Column('text', sa.Text(), nullable=False, comment='Текст сообщения'),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Флаг прочитанного сообщения'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время отправки'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Сообщения в чатах'
    )
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('user_chats',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False, comment='Уникальный идентификатор связи'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='ID чата'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания связи'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Связь пользователей с чатами'
    )
    op.create_index(op.f('ix_user_chats_chat_id'), 'user_chats', ['chat_id'], unique=False)
    op.create_index(op.f('ix_user_chats_user_id'), 'user_chats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_chats_user_id'), table_name='user_chats')
    op.drop_index(op.f('ix_user_chats_chat_id'), table_name='user_chats')
    op.drop_table('user_chats')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
